import type { Metadata } from "next";
import "./globals.css";
import { GoogleTagManager } from "@next/third-parties/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <!-- Google Tag Manager --> */}
      <GoogleTagManager gtmId="GTM-P4FBQL7L" />
      {/* <!-- End Google Tag Manager --> */}
      <body>{children}</body>
    </html>
  );
}
