import type { Metadata } from "next";
import { Nav } from "@/app/components/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav minimial={false} />
      {children}
    </>
  );
}
